# Reuse pre-existing partitions (no partitioning or formatting performed).
# Set device/boot_device/swap_device to your already-formatted partitions.
[disk]
    scheme = "existing_partitions"
    boot_type = "efi"
    device = "/dev/sdX3"
    boot_device = "/dev/sdX1"
    use_swap = true
    swap_size = "8GiB"
    swap_device = "/dev/sdX2"
    use_luks = false
    root_fs = "ext4"

[system]
    hostname = "gentoo"
    timezone = "UTC"
    keymap = "us"
    locales = ["C.UTF-8 UTF-8"]
    locale = "C.UTF-8"
    systemd_networkd = true
    systemd_networkd_interface_name = "en*"
    systemd_networkd_dhcp = true

[gentoo]
    mirror = "https://mirror.leaseweb.com/gentoo"
    arch = "amd64"
    stage3_variant = "systemd"
    profile = "default/linux/amd64/23.0/systemd"
    portage_sync_type = "git"
    portage_git_mirror = "https://anongit.gentoo.org/git/repo/sync/gentoo.git"
    use_portage_testing = false

[packages]
    enabling_repos = []
    enable_sshd = true
    enable_binpkg = true
    kernel_type = "bin"

[makeconf]
    options = ["jobs"]